/**
 * Medication names passed to AssemblyAI as key terms (`keyterms_prompt`), so
 * that a hesitant or mispronounced name is more likely to be *heard* correctly.
 * This only biases speech recognition. Nothing is corrected afterwards, and the
 * customer still confirms the readback. It is a vocabulary hint, not a database.
 *
 * AssemblyAI limits: at most 100 terms, each at most 50 characters. Distinctive
 * domain words work best; common English words can cause over-correction, so
 * none are listed here. Spelling and capitalization are used as written.
 */
export const MEDICATION_KEYTERMS: readonly string[] = [
  // Antibiotics, antifungals and antivirals
  "amoxicillin",
  "co-amoxiclav",
  "Augmentin",
  "azithromycin",
  "clarithromycin",
  "ciprofloxacin",
  "doxycycline",
  "flucloxacillin",
  "cefalexin",
  "cephalexin",
  "metronidazole",
  "nitrofurantoin",
  "trimethoprim",
  "fluconazole",
  "clotrimazole",
  "aciclovir",
  "acyclovir",
  // Pain and inflammation
  "paracetamol",
  "acetaminophen",
  "Panadol",
  "ibuprofen",
  "Nurofen",
  "naproxen",
  "diclofenac",
  "Voltaren",
  "celecoxib",
  "codeine",
  "tramadol",
  "aspirin",
  // Stomach and digestion
  "omeprazole",
  "esomeprazole",
  "pantoprazole",
  "lansoprazole",
  "famotidine",
  "metoclopramide",
  "domperidone",
  "ondansetron",
  "loperamide",
  // Heart, blood pressure and blood
  "atorvastatin",
  "simvastatin",
  "rosuvastatin",
  "amlodipine",
  "lisinopril",
  "enalapril",
  "ramipril",
  "losartan",
  "valsartan",
  "hydrochlorothiazide",
  "furosemide",
  "spironolactone",
  "bisoprolol",
  "metoprolol",
  "atenolol",
  "carvedilol",
  "warfarin",
  "clopidogrel",
  "apixaban",
  "rivaroxaban",
  // Diabetes and thyroid
  "metformin",
  "gliclazide",
  "glimepiride",
  "sitagliptin",
  "insulin glargine",
  "levothyroxine",
  // Steroids, asthma and allergy
  "prednisolone",
  "prednisone",
  "hydrocortisone",
  "salbutamol",
  "albuterol",
  "Ventolin",
  "budesonide",
  "fluticasone",
  "montelukast",
  "cetirizine",
  "Zyrtec",
  "loratadine",
  "fexofenadine",
  "chlorphenamine",
  "promethazine",
  // Mental health, nerves and sleep
  "sertraline",
  "fluoxetine",
  "citalopram",
  "escitalopram",
  "amitriptyline",
  "gabapentin",
  "pregabalin",
  "diazepam",
  "lorazepam",
  "zolpidem",
  // Other commonly dispensed
  "levonorgestrel",
  "tamsulosin",
  "finasteride",
  "sildenafil",
  "allopurinol",
  "colchicine",
  "ferrous sulfate",
];
